apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  annotations:
    keel.sh/policy: force # Tells the cluster to auto-update when Keel sees a new image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        # UPDATE THIS LINE to your lowercase GitHub info
        image: ghcr.io/pouriyamehr/website-v4:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - port: 80        # The port your domain will hit
      targetPort: 3000 # The port your Next.js app is listening on